routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/', 'HomeController@index')->name('home')->middleware('auth');
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');


Route::group(['middleware' => 'auth'], function () {
    Route::get('/users/list', ['as' => 'users.list', 'uses' => 'UserController@list']);
    Route::get('/user/{user}/edit', ['as' => 'user.edit', 'uses' => 'UserController@edit']);
    Route::post('/user/{user}/update', ['as' => 'user.update', 'uses' => 'UserController@update']);
    Route::get('/rapports', ['as' => 'rapports.index', 'uses' => 'RapportsController@index']);
    Route::get('/rapports/{rapport}', ['as' => 'rapports.show', 'uses' => 'RapportsController@show']);
    Route::get('/rapports/{rapport}/export', ['as' => 'rapports.export', 'uses' => 'RapportsController@export']);
    Route::get('/rapports/{rapport}/edit', ['as' => 'rapports.edit', 'uses' => 'RapportsController@edit']);
    Route::post('/rapports/{rapport}/{user}/update', ['as' => 'rapports.update', 'uses' => 'RapportsController@update']);
    Route::get('/rapports/{client}/list', ['as' => 'rapports.list', 'uses' => 'RapportsController@list']);
    Route::get('/rapports/{user}/create', ['as' => 'rapports.create', 'uses' => 'RapportsController@create']);
    Route::post('/rapports/{user}/store', ['as' => 'rapports.store', 'uses' => 'RapportsController@store']);
    Route::get('/stats/{client}/{range?}', ['as' => 'stats', 'uses' => 'HomeController@stats']);
});

Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function(){
    Route::resource('/users', 'UsersController', ['except' => ['create', 'store']]);
    Route::get('/users/{type}/create', ['as' => 'users.create', 'uses' => 'UsersController@create']);
    Route::post('/users/{type}/store', ['as' => 'users.store', 'uses' => 'UsersController@store']);
    Route::post('/users/{user}/{type}/destroy', ['as' => 'users.destroy', 'uses' => 'UsersController@destroy']);
    Route::get('/users/list/{type}', ['as' => 'users.list', 'uses' => 'UsersController@list']);
    Route::resource('/formulaires','FormulairesController', ['except' => ['show', 'create', 'store']]);
    Route::get('/formulaires/{user}/create/', ['as' => 'formulaires.create', 'uses' => 'FormulairesController@create']);
    Route::post('/formulaires/{user}/store/', ['as' => 'formulaires.store', 'uses' => 'FormulairesController@store']);
    Route::resource('/analyses','AnalysesController', ['except' => ['show']]);
    Route::post('/analyses/sort', '\Rutorika\Sortable\SortableController@sort');
    Route::resource('/equipements','EquipementsController', ['except' => ['show']]);
});

app/Formulaire.php
<?php

namespace App;

use App\Champ;
use Illuminate\Database\Eloquent\Model;

class Formulaire extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'client_id',
        'equipement_id',
        'equipement_titre'
    ];

    public function client() {
        return $this->belongsTo('\App\User', 'client_id');
    }

    public function equipement() {
        return $this->belongsTo('App\Equipement');
    }

    public function champs() {
        return $this->hasMany('App\Champ');
    }

    public function champ($analyse_id, $type) {
        $champ = Champ::where(['analyse_id' => $analyse_id, 'formulaire_id' => $this->id])->first();
            if(isset($champ->$type)) {
                return $champ->$type;
            }
    }

    public function hasChamp($analyse_id)
    {
        foreach($this->champs as $champ) {
            if($champ->analyse_id == $analyse_id) {
                return true;
            }
        }

        return false;
    }

    public function getChamp($analyse_id)
    {
        $champ = Champ::where('analyse_id', $analyse_id)->where('formulaire_id', $this->id)->first();

        return $champ;
    }

    /**
     * Get the equipment name.
     *
     * @param  string  $value
     * @return string
     */
    public function getEquipementTitreAttribute($value)
    {
        if('' == $value) {
            $value = $this->equipement->nom;
        }

        /*if(strlen($value) > 16) {
            return str_replace(' ', '<br>', $value);
        }*/

        return $value;
    }
}

app/Http/Controllers/Admin/FormulairesController.php
<?php

namespace App\Http\Controllers\Admin;

use Gate;
use App\User;
use App\Champ;
use App\Analyse;
use App\Formulaire;
use App\Equipement;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class FormulairesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $formulaires = Formulaire::all();
        return view('admin.formulaires.index')->with('formulaires', $formulaires);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(User $user)
    {
        $analyses = Analyse::sorted()->get();
        $equipements = Equipement::all();

        return view('admin.formulaires.create', compact([
            'analyses',
            'user',
            'equipements'
            ]));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, User $user)
    {
        $analyseCount = Analyse::orderBy('id', 'desc')->first();
        $analyses = $request->all();

        $formulaire = Formulaire::create([
            'client_id' => $user->id,
            'equipement_id' => $analyses['equipement_id'],
            'equipement_titre' => $analyses['equipement_titre'] ?? ''
        ]);

        for ($key = 1; $key <= $analyseCount->id; $key++) {
            if(isset($analyses["is_active_$key"])) {
                $unite = isset($analyses["unite_$key"]) ? $analyses["unite_$key"] : '';
                $min = isset($analyses["min_$key"]) ? $analyses["min_$key"] : '';
                $max = isset($analyses["max_$key"]) ? $analyses["max_$key"] : '';
                $jaune_min = isset($analyses["jaune_min_$key"]) ? $analyses["jaune_min_$key"] : '';
                $jaune_max = isset($analyses["jaune_max_$key"]) ? $analyses["jaune_max_$key"] : '';
                $orange_min = isset($analyses["orange_min_$key"]) ? $analyses["orange_min_$key"] : '';
                $orange_max = isset($analyses["orange_max_$key"]) ? $analyses["orange_max_$key"] : '';
                $rouge_min = isset($analyses["rouge_min_$key"]) ? $analyses["rouge_min_$key"] : '';
                $rouge_max = isset($analyses["rouge_max_$key"]) ? $analyses["rouge_max_$key"] : '';
                $result = [
                    'analyse_id' => $key,
                    'formulaire_id' => $formulaire->id,
                    'min' => $min,
                    'max' => $max,
                    'jaune_min' => $jaune_min,
                    'jaune_max' => $jaune_max,
                    'orange_min' => $orange_min,
                    'orange_max' => $orange_max,
                    'rouge_min' => $rouge_min,
                    'rouge_max' => $rouge_max,
                ];
                Champ::create($result);
            }
        }

        return redirect()->route('admin.users.show', $user)->withStatus(__('Nouvel équipement ajouté.'));
    }

    protected function getIdFromKey($key)
    {
        return ;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Formulaire  $formulaire
     * @return \Illuminate\Http\Response
     */
    public function edit(Formulaire $formulaire)
    {
        if(Gate::denies('edit-users')){
            return redirect()->route('admin.formulaires.index');
        }

        $analyses = Analyse::sorted()->get();
        $equipements = Equipement::all();

        return view('admin.formulaires.edit', compact('formulaire', 'analyses', 'equipements'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Formulaire  $formulaire
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Formulaire $formulaire)
    {
        $analyseCount = Analyse::orderBy('id', 'desc')->first();
        $analyses = $request->all();

        $formulaire->update([
            'client_id' => $formulaire->client->id,
            'equipement_id' => $analyses['equipement_id'],
            'equipement_titre' => $analyses['equipement_titre'] ?? ''
        ]);

        for ($key = 1; $key <= $analyseCount->id; $key++) {
            if(isset($analyses["is_active_$key"]) && $analyses["is_active_$key"] == 1) {
                $result = [
                    'analyse_id' => $key,
                    'formulaire_id' => $formulaire->id,
                    'unite' => isset($analyses["unite_$key"]) ? $analyses["unite_$key"] : '',
                    'min' => isset($analyses["min_$key"]) ? $analyses["min_$key"] : '',
                    'max' => isset($analyses["max_$key"]) ? $analyses["max_$key"] : '',
                    'jaune_min' => isset($analyses["jaune_min_$key"]) ? $analyses["jaune_min_$key"] : '',
                    'jaune_max' => isset($analyses["jaune_max_$key"]) ? $analyses["jaune_max_$key"] : '',
                    'orange_min' => isset($analyses["orange_min_$key"]) ? $analyses["orange_min_$key"] : '',
                    'orange_max' => isset($analyses["orange_max_$key"]) ? $analyses["orange_max_$key"] : '',
                    'rouge_min' => isset($analyses["rouge_min_$key"]) ? $analyses["rouge_min_$key"] : '',
                    'rouge_max' => isset($analyses["rouge_max_$key"]) ? $analyses["rouge_max_$key"] : '',
                ];

                $oldChamp = Champ::where(['analyse_id' => $key, 'formulaire_id' => $formulaire->id])->first();

                if($oldChamp) {
                    $oldChamp->update($result);
                } else {
                    Champ::create($result);
                }
            } else {
                $oldChamp = Champ::where(['analyse_id' => $key, 'formulaire_id' => $formulaire->id])->first();

                if($oldChamp) {
                    $oldChamp->delete();
                }
            }
        }

        return redirect()->route('admin.users.show', $formulaire->client)->withStatus(__('Formulaire sauvegardé'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Formulaire  $formulaire
     * @return \Illuminate\Http\Response
     */
    public function destroy(Formulaire $formulaire)
    {
        $formulaire->delete();

        return redirect()->route('admin.users.show', $formulaire->client)->withStatus(__('Formulairee supprimé.'));
    }
}

resources/views/admin/formulaires/create.blade.php
@extends('layouts.app', ['activePage' => 'formulaires', 'titlePage' => __('Formulaire')])

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Ajouter un équipement pour {{ $user->compagnie }}</div>
                <div class="card-body">
                    <form action="{{ route('admin.formulaires.store', $user) }}" method="post">
                        @csrf
                        @method('post')
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="equipement_id">Équipement</label>
                                <select id="equipement_id" class="form-control" name="equipement_id">
                                    @foreach($equipements as $equipement)
                                        <option value="{{ $equipement->id }}">{{ $equipement->nom }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="equipement_titre">Nom de l'équipement (si différent)</label>
                                <input type="text" id="equipement_titre" class="form-control" name="equipement_titre">
                            </div>
                        </div>
                        <hr>
                        <h3>Analyses</h3>

                        @foreach($analyses as $analyse)
                        <div class="form-row analyse">
                            <div class="form-group col-md-3">
                                <input type="checkbox" name="is_active_{{ $analyse->id }}" value="1"> &nbsp;
                                <label for="is_active_{{ $analyse->id }}">{{ $analyse->titre }}</label>
                            </div>
                            @if($analyse->type == 'text' && $analyse->groupe == 'materiel')
                            <div class="form-group col-md-3">
                                <input type="text" class="form-control" id="unite_{{ $analyse->id }}" name="unite_{{ $analyse->id }}" placeholder="Unité">
                            </div>
                            <div class="form-group col-md-3">
                                <input type="text" class="form-control" id="min_{{ $analyse->id }}" name="min_{{ $analyse->id }}" placeholder="Minimum">
                            </div>
                            <div class="form-group col-md-3">
                                <input type="text" class="form-control" id="max_{{ $analyse->id }}" name="max_{{ $analyse->id }}" placeholder="Maximum">
                            </div>
                        </div>
                            <div class="form-row">
                                <div class="form-group col-md-2">
                                    <input type="text" class="form-control champ-jaune" id="jaune_min_{{ $analyse->id }}" name="jaune_min_{{ $analyse->id }}" placeholder="Minimum">
                                </div>
                                <div class="form-group col-md-2">
                                    <input type="text" class="form-control champ-jaune" id="jaune_max_{{ $analyse->id }}" name="jaune_max_{{ $analyse->id }}" placeholder="Maximum">
                                </div>
                                <div class="form-group col-md-2">
                                    <input type="text" class="form-control champ-orange" id="orange_min_{{ $analyse->id }}" name="orange_min_{{ $analyse->id }}" placeholder="Minimum">
                                </div>
                                <div class="form-group col-md-2">
                                    <input type="text" class="form-control champ-orange" id="orange_max_{{ $analyse->id }}" name="orange_max_{{ $analyse->id }}" placeholder="Maximum">
                                </div>
                                <div class="form-group col-md-2">
                                    <input type="text" class="form-control champ-rouge" id="rouge_min_{{ $analyse->id }}" name="rouge_min_{{ $analyse->id }}" placeholder="Minimum">
                                </div>
                                <div class="form-group col-md-2">
                                    <input type="text" class="form-control champ-rouge" id="rouge_max_{{ $analyse->id }}" name="rouge_max_{{ $analyse->id }}" placeholder="Maximum">
                                </div>
                            @endif
                        </div>
                        @endforeach
                        <button type="submit" class="btn btn-primary">Sauvegarder</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/formulaires/edit.blade.php
@extends('layouts.app', ['activePage' => 'formulaires', 'titlePage' => __('Formulaire')])

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Édition du formulaire {{ $formulaire->id }}</div>
                <div class="card-body">
                    <form action="{{ route('admin.formulaires.update', $formulaire) }}" method="POST">
                        @csrf
                        {{ method_field('PUT') }}
                        <h3>Info Client</h3>
                        <div class="row">
                            <div class="col-md-12">
                                {{ $formulaire->client->compagnie }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="equipement_id">Équipement</label>
                                <select id="equipement_id" class="form-control" name="equipement_id">
                                    @foreach($equipements as $equipement)
                                        <option value="{{ $equipement->id }}" {{ $formulaire->equipement_id == $equipement->id ? 'selected="selected"' : '' }}>{{ $equipement->nom }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="equipement_titre">Nom de l'équipement (si différent)</label>
                                <input type="text" id="equipement_titre" class="form-control" name="equipement_titre" value="{{ $formulaire->equipement_titre }}">
                            </div>
                        </div>
                        <hr>

                        <h3>Analyses</h3>

                        @foreach($analyses as $analyse)
                            <div class="form-row analyse">
                                <div class="form-group col-md-3">
                                    <input type="hidden" name="is_active_{{ $analyse->id }}" value="0">
                                    <input type="checkbox" name="is_active_{{ $analyse->id }}" value="1"{{ $formulaire->hasChamp($analyse->id) ? 'checked="checked"' : '' }}> &nbsp;
                                    <label for="is_active_{{ $analyse->id }}">{{ $analyse->titre }}</label>
                                </div>
                                @if($analyse->type == 'text' && $analyse->groupe == 'materiel')
                                <div class="form-group col-md-3">
                                    <input type="text" class="form-control" id="unite_{{ $analyse->id }}" name="unite_{{ $analyse->id }}" placeholder="Unité" value="{{ $formulaire->champ($analyse->id, 'unite') }}">
                                </div>
                                <div class="form-group col-md-3">
                                    <input type="text" class="form-control" id="min_{{ $analyse->id }}" name="min_{{ $analyse->id }}" placeholder="Minimum" value="{{ $formulaire->champ($analyse->id, 'min') }}">
                                </div>
                                <div class="form-group col-md-3">
                                    <input type="text" class="form-control" id="max_{{ $analyse->id }}" name="max_{{ $analyse->id }}" placeholder="Maximum" value="{{ $formulaire->champ($analyse->id, 'max') }}">
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-2">
                                    <input type="text" class="form-control champ-jaune" id="jaune_min_{{ $analyse->id }}" name="jaune_min_{{ $analyse->id }}" placeholder="Minimum" value="{{ $formulaire->champ($analyse->id, 'jaune_min') }}">
                                </div>
                                <div class="form-group col-md-2">
                                    <input type="text" class="form-control champ-jaune" id="jaune_max_{{ $analyse->id }}" name="jaune_max_{{ $analyse->id }}" placeholder="Maximum" value="{{ $formulaire->champ($analyse->id, 'jaune_max') }}">
                                </div>
                                <div class="form-group col-md-2">
                                    <input type="text" class="form-control champ-orange" id="orange_min_{{ $analyse->id }}" name="orange_min_{{ $analyse->id }}" placeholder="Minimum" value="{{ $formulaire->champ($analyse->id, 'orange_min') }}">
                                </div>
                                <div class="form-group col-md-2">
                                    <input type="text" class="form-control champ-orange" id="orange_max_{{ $analyse->id }}" name="orange_max_{{ $analyse->id }}" placeholder="Maximum" value="{{ $formulaire->champ($analyse->id, 'orange_max') }}">
                                </div>
                                <div class="form-group col-md-2">
                                    <input type="text" class="form-control champ-rouge" id="rouge_min_{{ $analyse->id }}" name="rouge_min_{{ $analyse->id }}" placeholder="Minimum" value="{{ $formulaire->champ($analyse->id, 'rouge_min') }}">
                                </div>
                                <div class="form-group col-md-2">
                                    <input type="text" class="form-control champ-rouge" id="rouge_max_{{ $analyse->id }}" name="rouge_max_{{ $analyse->id }}" placeholder="Maximum" value="{{ $formulaire->champ($analyse->id, 'rouge_max') }}">
                                </div>
                                @endif
                            </div>
                        @endforeach
                        <button type="submit" class="btn btn-primary">Sauvegarder</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/formulaires/index.blade.php
@extends('layouts.app', ['activePage' => 'formulaires', 'titlePage' => __('Formulaires')])

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Formulaires <a href="{{ route('admin.formulaires.create', $user) }}" class="btn btn-link float-right"><i class="fa fa-plus"></i></a></div>

                <div class="card-body">
                    <table class="table">
                            <thead>
                              <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Compagnie</th>
                                <th scope="col">Équipement</th>
                                <th scope="col">Action</th>
                              </tr>
                            </thead>
                            <tbody>
                            @foreach($formulaires as $formulaire)
                              <tr>
                                <th scope="row">{{ $formulaire->id }}</th>
                                <td>{{ $formulaire->client->compagnie }}</td>
                                <td>{{ $formulaire->equipement->nom }}</td>
                                <td>
                                    <a href="{{ route('admin.formulaires.edit', $formulaire) }}"><button type="button" class="btn btn-link float-left"><i class="fa fa-pencil"></i></button></a>
                                    <form action="{{ route('admin.formulaires.destroy', $formulaire) }}" method="POST" class="float-left">
                                        @csrf
                                        {{ method_field('DELETE') }}
                                        <button type="button" class="btn btn-link"><i class="fa fa-trash-o"></i></button>
                                    </form>
                                </td>
                              </tr>
                            @endForeach
                            </tbody>
                          </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection