routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/', 'HomeController@index')->name('home')->middleware('auth');
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');


Route::group(['middleware' => 'auth'], function () {
    Route::get('/users/list', ['as' => 'users.list', 'uses' => 'UserController@list']);
    Route::get('/user/{user}/edit', ['as' => 'user.edit', 'uses' => 'UserController@edit']);
    Route::post('/user/{user}/update', ['as' => 'user.update', 'uses' => 'UserController@update']);
    Route::get('/rapports', ['as' => 'rapports.index', 'uses' => 'RapportsController@index']);
    Route::get('/rapports/{rapport}', ['as' => 'rapports.show', 'uses' => 'RapportsController@show']);
    Route::get('/rapports/{rapport}/export', ['as' => 'rapports.export', 'uses' => 'RapportsController@export']);
    Route::get('/rapports/{rapport}/edit', ['as' => 'rapports.edit', 'uses' => 'RapportsController@edit']);
    Route::post('/rapports/{rapport}/{user}/update', ['as' => 'rapports.update', 'uses' => 'RapportsController@update']);
    Route::get('/rapports/{client}/list', ['as' => 'rapports.list', 'uses' => 'RapportsController@list']);
    Route::get('/rapports/{user}/create', ['as' => 'rapports.create', 'uses' => 'RapportsController@create']);
    Route::post('/rapports/{user}/store', ['as' => 'rapports.store', 'uses' => 'RapportsController@store']);
    Route::get('/stats/{client}/{range?}', ['as' => 'stats', 'uses' => 'HomeController@stats']);
});

Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function(){
    Route::resource('/users', 'UsersController', ['except' => ['create', 'store']]);
    Route::get('/users/{type}/create', ['as' => 'users.create', 'uses' => 'UsersController@create']);
    Route::post('/users/{type}/store', ['as' => 'users.store', 'uses' => 'UsersController@store']);
    Route::post('/users/{user}/{type}/destroy', ['as' => 'users.destroy', 'uses' => 'UsersController@destroy']);
    Route::get('/users/list/{type}', ['as' => 'users.list', 'uses' => 'UsersController@list']);
    Route::resource('/formulaires','FormulairesController', ['except' => ['show', 'create', 'store']]);
    Route::get('/formulaires/{user}/create/', ['as' => 'formulaires.create', 'uses' => 'FormulairesController@create']);
    Route::post('/formulaires/{user}/store/', ['as' => 'formulaires.store', 'uses' => 'FormulairesController@store']);
    Route::resource('/analyses','AnalysesController', ['except' => ['show']]);
    Route::post('/analyses/sort', '\Rutorika\Sortable\SortableController@sort');
    Route::resource('/equipements','EquipementsController', ['except' => ['show']]);
});

app/User.php
<?php

namespace App;

use App\Rapport;
use App\Formulaire;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, Notifiable;

    protected $appends = [
        'company_id'
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'avatar', 'compagnie', 'poste', 'operateur_clients', 'is_active', 'is_principal', 'is_rapports', 'adresse', 'ville', 'province', 'code_postal', 'telephone', 'horaire_jours', 'horaire_ouverture', 'horaire_fermeture', 'horaire_feries', 'horaire_mensuel'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getImageAttribute()
    {
        return $this->avatar;
    }

    public function roles() {
        return $this->belongsToMany('App\Role');
    }

    public function formulaires() {
        return $this->hasMany('App\Formulaire', 'client_id', 'company_id');
    }

    public function rapports() {

        return $this->hasMany('App\Rapport', 'client_id', 'company_id')->orderBy('updated_at', 'DESC');
    }

    public function hasAnyRoles($roles) {

        if($this->roles()->whereIn('name', $roles)->first()) {
            return true;
        }

        return false;
    }

    public function hasRole($role) {

        if($this->roles()->where('name', $role)->first()) {
            return true;
        }

        return false;
    }

    public function hasAnyAnalyse($analyse_id)
    {
        foreach($this->formulaires as $formulaire) {
            if($formulaire->hasChamp($analyse_id)) {
                return true;
            }
        }

        return false;
    }

    public function clients()
    {
        $clients = [];
        $users = $this->all();

        foreach($users as $user) {
            if($user->hasRole('client')) {
                $clients[] = $user;
            }
        }

        return $clients;
    }

    public function operateurClients()
    {
        $clients = [];
        $users = json_decode($this->operateur_clients, true);

        if(null !== $users) {
            return $users;
        }

        return $clients;
    }
    
    public function companyId()
    {
        $company = $this->where('compagnie', $this->compagnie)->where('is_principal', 1)->first();

        return $company->id;
    }

    public function getCompanyIdAttribute() {
        $company = $this->where('compagnie', $this->compagnie)->where('is_principal', 1)->first();
        
        if($company) {
            return $company->id;
        }

        return $this->id;
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use App\Role;
use Storage;
use App\Equipement;
use Gate;
use Hash;
use Illuminate\Http\Request;
use App\Http\Requests\UserRequest;
use App\Http\Controllers\Controller;

class UsersController extends Controller
{
    public function __construct() {
        $this->middleware('auth');
        $this->middleware('auth.admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::whereHas('roles', function($q) {
            $q->where('name', 'client');
        })->get();

        return view('admin.users.index')->with('users', $users);
    }

    public function list($type)
    {
        $users = User::whereHas('roles', function($q) use($type) {
            $q->where('name', $type);
            if($type == 'client') {
                $q->orWhere('name', 'contact');
            }
        })->orderBy('compagnie', 'ASC')->get();

        $compagnies = $users->groupBy('compagnie');
        $compagnies->toArray();

        return view('admin.users.list')->with([
            'compagnies' => $compagnies,
            'type' => $type
            ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('admin.users.show')->with('user', $user);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($type)
    {
        if(Gate::denies('edit-users')){
            return redirect()->route('admin.users.index');
        }

        $roles = Role::all();
        $equipements = Equipement::all();
        $clients = User::whereHas('roles', function($q) {
            $q->where('name', 'client');
        })->get();

        $compagnies = User::distinct('compagnie')->pluck('compagnie');

        return view('admin.users.create')->with([
            'roles' => $roles,
            'equipements' => $equipements,
            'clients' => $clients,
            'compagnies' => $compagnies,
            'type' => $type
        ]);
    }

    /**
     * Store a newly created user in storage
     *
     * @param  \App\Http\Requests\UserRequest  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request, $type)
    {
        $request->validate([
            'name'   =>  'required',
            'avatar' =>  'image|mimes:jpeg,png,jpg,gif|max:2048',
            'email' => 'required|email|unique:users',
        ]);

        if ($request->hasFile('avatarFile')) {
                $avatarName = str_replace(' ', '_', $request->name).'_avatar'.time().'.'.$request->file('avatarFile')->extension();
                $request->file('avatarFile')->move(public_path('assets/images/avatars'), $avatarName);
                $request['avatar'] = $avatarName;
        }

        $formData = $request->merge(['password' => Hash::make($request->get('password'))])->all();
        $formData['operateur_clients'] = isset($formData['operateur_clients']) ? json_encode($formData['operateur_clients']) : '';
        $formData['horaire_jours'] = isset($formData['horaire_jours']) ? json_encode($formData['horaire_jours']) : '';
        $formData['horaire_feries'] = isset($formData['horaire_feries']) ? $formData['horaire_feries'] : '0';
        $formData['horaire_mensuel'] = isset($formData['horaire_mensuel']) ? $formData['horaire_mensuel'] : '0';
        $formData['compagnie'] = isset($formData['new-compagnie']) ? $formData['new-compagnie'] : $formData['compagnie'];

        $user = User::create($formData);

        foreach($formData['roles'] as $role) {
            $roleName = Role::where('id', $role)->first();
            $user->roles()->attach($roleName);
        }

        return redirect()->route('admin.users.list', $type)->withStatus(__('Utilisateur ajouté.'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        if(Gate::denies('edit-users')){
            return redirect()->route('admin.users.index');
        }

        $roles = Role::all();
        $equipements = Equipement::all();
        $clients = User::whereHas('roles', function($q) {
            $q->where('name', 'client');
        })->orderBy('compagnie', 'ASC')->get();
        $compagnies = User::distinct('compagnie')->pluck('compagnie');

        return view('admin.users.edit')->with([
            'user' => $user,
            'roles' => $roles,
            'equipements' => $equipements,
            'clients' => $clients,
            'compagnies' => $compagnies
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $request->validate([
            'name'   =>  'required',
            'avatar' =>  'image|mimes:jpeg,png,jpg,gif|max:2048'
        ]);

        if ($request->hasFile('avatarFile')) {
                $avatarName = str_replace(' ', '_', $request->name).'_avatar'.time().'.'.$request->file('avatarFile')->extension();
                $request->file('avatarFile')->move(public_path('assets/images/avatars'), $avatarName);
                $request['avatar'] = $avatarName;
        }

        $hasPassword = $request->get('password');
        $formData = $request->merge(['password' => Hash::make($request->get('password'))])
        ->except([$hasPassword ? '' : 'password']);
        $formData['horaire_jours'] = isset($formData['horaire_jours']) ? json_encode($formData['horaire_jours']) : null;
        $formData['horaire_feries'] = isset($formData['horaire_feries']) ? '1' : '0';
        $formData['horaire_mensuel'] = isset($formData['horaire_mensuel']) ? $formData['horaire_mensuel'] : '0';

        $user->update($formData);
        $user->roles()->sync($request->roles);

        return redirect()->route('admin.users.show', $user);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user, $type)
    {
        if(Gate::denies('edit-users')){
            return redirect()->route('admin.users.list', $type);
        }

        $user->roles()->detach();
        $user->delete();

        return redirect()->route('admin.users.list', $type);
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.app', ['activePage' => 'user-management', 'titlePage' => __('Users')])

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Ajouter un client</div>

                <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ dd($error) }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form action="{{ route('admin.users.store', $type) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('post')
                        <h3>Type</h3>
                        @foreach($roles as $role)
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="checkbox" name="roles[]" value="{{ $role->id }}" {{ $role->name == $type ? 'checked="checked"' : '' }}>
                                <label class="form-check-label">{{ $role->name }}</label>
                            </div>
                        @endforeach
                        <hr>
                        <h3>Détails</h3>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="name">Nom</label>
                                <input type="text" class="form-control" id="name" name="name">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="email">Courriel</label>
                                <input type="email" class="form-control" id="email" name="email">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="password">Mot de passe</label>
                                <input type="password" class="form-control" id="password"  name="password">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="confirm-password">Confirmer le mot de passe</label>
                                <input type="password" class="form-control" id="confirm-password" name="confirm_password">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="avatarFile">Photo</label>
                                <input type="file" class="form-control-file" name="avatarFile" id="avatarFile">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="checkbox" name="is_principal" value="1">
                                    <label class="form-check-label">Contact principal</label>
                                </div>
                            </div>
                            <div class="form-group col-md-6">
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="checkbox" name="is_rapports" value="1">
                                    <label class="form-check-label">Reçoit les rapports</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="compagnie">Compagnie</label>
                                <select id="compagnie" name="compagnie" class="form-control">
                                @foreach($compagnies as $compagnie)
                                    <option value="{{ $compagnie }}">{{ $compagnie }}</option>
                                @endForeach
                                </select>
                                 Nouvelle compagnie: <input type="text" class="form-control" id="new-compagnie" name="new-compagnie">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="poste">Poste</label>
                                <input type="text" class="form-control" id="poste"  name="poste" name="poste">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="adresse">Adresse</label>
                                <input type="text" class="form-control" id="adresse" name="adresse">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="ville">Ville</label>
                                <input type="text" class="form-control" id="ville" name="ville">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="province">Province</label>
                                <select id="province" name="province" class="form-control">
                                    <option value="QC">QC</option>
                                    <option value="ON">ON</option>
                                </select>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="code_postal">Code postal</label>
                                <input type="text" class="form-control" id="code_postal"  name="code_postal">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="telephone">Téléphone</label>
                                <input type="text" class="form-control" id="telephone" name="telephone">
                            </div>
                        </div>
                        @if(auth()->user()->hasRole('admin') )
                        <hr>
                        <h3>Clients</h3>
                        <div class="row">
                        @foreach($clients as $client)
                        <div class="form-check col-md-6">
                            <input class="form-check-input" type="checkbox" name="operateur_clients[]" value="{{ $client->id }}">
                            <label class="form-check-label">{{ $client->compagnie }}</label>
                        </div>
                        @endforeach
                        </div>
                        @endif
                        <hr>
                        <h3>Entreprise</h3>
                        <h6>Jours ouvrables</h6>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="checkbox" name="horaire_jours[]" value="lundi">
                            <label class="form-check-label">Lundi</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="checkbox" name="horaire_jours[]" value="mardi">
                            <label class="form-check-label">Mardi</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="checkbox" name="horaire_jours[]" value="mercredi">
                            <label class="form-check-label">Mercredi</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="checkbox" name="horaire_jours[]" value="jeudi">
                            <label class="form-check-label">Jeudi</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="checkbox" name="horaire_jours[]" value="vendredi">
                            <label class="form-check-label">Vendredi</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="checkbox" name="horaire_jours[]" value="samedi">
                            <label class="form-check-label">Samedi</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="checkbox" name="horaire_jours[]" value="dimanche">
                            <label class="form-check-label">Dimanche</label>
                        </div>
                        <div class="form-row">
                            <div class="input-group date col-md-6" id="ouverturetimepicker" data-target-input="nearest">
                                <input type="text" class="form-control datetimepicker-input" data-target="#ouverturetimepicker" id="horaire_ouverture" name="horaire_ouverture">
                                <div class="input-group-append" data-target="#ouverturetimepicker" data-toggle="datetimepicker">
                                    <div class="input-group-text"><i class="fa fa-clock-o"></i></div>
                                </div>
                            </div>
                            <div class="input-group date col-md-6" id="fermeturetimepicker" data-target-input="nearest">
                                <input type="text" class="form-control datetimepicker-input" data-target="#fermeturetimepicker" name="horaire_fermeture" />
                                <div class="input-group-append" data-target="#fermeturetimepicker" data-toggle="datetimepicker">
                                    <div class="input-group-text"><i class="fa fa-clock-o"></i></div>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="custom-control custom-switch col-md-6 text-center">
                                <input type="checkbox" class="custom-control-input" id="horaire_feries" name="horaire_feries" value="1">
                                <label class="custom-control-label" for="horaire_feries">Jours fériés</label>
                            </div>
                            <div class="custom-control custom-switch col-md-6 text-center">
                                <input type="checkbox" class="custom-control-input" id="horaire_mensuel" name="horaire_mensuel" value="1">
                                <label class="custom-control-label" for="horaire_mensuel">Visite mensuelle</label>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Sauvegarder</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('js')
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
  <script>
    $(document).ready(function(){
            $('#ouverturetimepicker').datetimepicker({
                format: 'LT'
            });
            $('#fermeturetimepicker').datetimepicker({
                format: 'LT'
            });
        });
  </script>
@endpush

resources/views/admin/users/show.blade.php
@extends('layouts.app', ['activePage' => 'user-management', 'titlePage' => __('Users')])

@section('content')

    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card social">
                <div class="profile-header d-flex justify-content-between justify-content-center">
                    <div class="d-flex">
                        <div class="details">
                            <h3 class="mb-0">{{ $user->compagnie }}</h3>
                            <span class="text-light">
                                {!! $user->adresse ? $user->adresse . '<br>' : '' !!}
                                {!! $user->ville ? $user->ville . ', ' . $user->province . '<br>' : '' !!}
                                {!! $user->code_postal ? $user->code_postal . '<br>' : '' !!}
                            </span>
                            @if($user->avatar != 'avatar.jpg')
                            <img src="/assets/images/avatars/{{ $user->avatar }}" class="user-photo" alt="{{ $user->name }}" style="float:left;margin:0 5px 0 0;height:40px; width:40px;object-fit: cover;border-radius: 4px;">
                            @endif
                            <p class="mb-0">
                                <span>Contact: <strong>{{ $user->name }}</strong> {{ $user->poste }}</span><br>
                                <span>Tel: <strong>{{ $user->telephone }}</strong></span><br>
                                <span>Email: <strong>{{ $user->email }}</strong></span><br>
                            </p>
                        </div>
                    </div>
                    <div>
                        <a href="{{ route('admin.users.edit', $user) }}" class="btn btn-link float-right"><i class="fa fa-pencil"></i></a>
                    </div>
                </div>
            </div>
            @if($user->hasRole('client') || $user->hasRole('contact'))
            <a href="{{ route('stats', $user) }}" class="btn btn-primary">Statistiques</a>
            <div class="card">
                <div class="card-header">Équipements <a href="{{ route('admin.formulaires.create', $user) }}" class="btn btn-primary float-right"><i class="fa fa-plus"></i></a></div>
                <div class="card-body">
                    <table class="table">
                        <tbody>
                        @foreach($user->formulaires as $formulaire)
                            <tr>
                            <th scope="row">{!! $formulaire->equipement_titre !!}</th>
                            <td>
                                <a href="{{ route('admin.formulaires.edit', $formulaire) }}"><button type="button" class="btn btn-link float-left"><i class="fa fa-pencil"></i></button></a>
                                <form action="{{ route('admin.formulaires.destroy', $formulaire) }}" method="POST" class="float-left">
                                    @csrf
                                    @method('delete')
                                    <button type="button" class="btn btn-link" onclick="confirm('{{ __("Êtes-vous certain de vouloir supprimer cet équipement?") }}') ? this.parentElement.submit() : ''">
                                        <i class="fa fa-trash-o"></i>
                                    </button>
                                </form>
                            </td>
                            </tr>
                        @endForeach
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card">
                <div class="card-header">Rapports <a href="{{ route('rapports.create', $user) }}" class="btn btn-primary float-right"><i class="fa fa-plus"></i></a></div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Date</th>
                                <th scope="col">Opérateur</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($user->rapports as $rapport)
                            <tr>
                            <td>{{ $rapport->updated_at }}</th>
                            <td>{{ $rapport->operateur->name }}</th>
                            <td>
                                <a href="{{ route('rapports.show', $rapport) }}"><button type="button" class="btn btn-link float-left"><i class="fa fa-eye"></i></button></a>
                                <a href="{{ route('rapports.export', $rapport) }}"><button type="button" class="btn btn-link float-left"><i class="fa fa-file-pdf-o"></i></button></a>
                                <a href="{{ route('rapports.edit', $rapport) }}"><button type="button" class="btn btn-link"><i class="fa fa-pencil"></i></button></a>
                            </td>
                            </tr>
                        @endForeach
                        </tbody>
                    </table>
                </div>
            </div>
            @endif
        </div>
    </div>

@endsection