routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/', 'HomeController@index')->name('home')->middleware('auth');
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');


Route::group(['middleware' => 'auth'], function () {
    Route::get('/users/list', ['as' => 'users.list', 'uses' => 'UserController@list']);
    Route::get('/user/{user}/edit', ['as' => 'user.edit', 'uses' => 'UserController@edit']);
    Route::post('/user/{user}/update', ['as' => 'user.update', 'uses' => 'UserController@update']);
    Route::get('/rapports', ['as' => 'rapports.index', 'uses' => 'RapportsController@index']);
    Route::get('/rapports/{rapport}', ['as' => 'rapports.show', 'uses' => 'RapportsController@show']);
    Route::get('/rapports/{rapport}/export', ['as' => 'rapports.export', 'uses' => 'RapportsController@export']);
    Route::get('/rapports/{rapport}/edit', ['as' => 'rapports.edit', 'uses' => 'RapportsController@edit']);
    Route::post('/rapports/{rapport}/{user}/update', ['as' => 'rapports.update', 'uses' => 'RapportsController@update']);
    Route::get('/rapports/{client}/list', ['as' => 'rapports.list', 'uses' => 'RapportsController@list']);
    Route::get('/rapports/{user}/create', ['as' => 'rapports.create', 'uses' => 'RapportsController@create']);
    Route::post('/rapports/{user}/store', ['as' => 'rapports.store', 'uses' => 'RapportsController@store']);
    Route::get('/stats/{client}/{range?}', ['as' => 'stats', 'uses' => 'HomeController@stats']);
});

Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function(){
    Route::resource('/users', 'UsersController', ['except' => ['create', 'store']]);
    Route::get('/users/{type}/create', ['as' => 'users.create', 'uses' => 'UsersController@create']);
    Route::post('/users/{type}/store', ['as' => 'users.store', 'uses' => 'UsersController@store']);
    Route::post('/users/{user}/{type}/destroy', ['as' => 'users.destroy', 'uses' => 'UsersController@destroy']);
    Route::get('/users/list/{type}', ['as' => 'users.list', 'uses' => 'UsersController@list']);
    Route::resource('/formulaires','FormulairesController', ['except' => ['show', 'create', 'store']]);
    Route::get('/formulaires/{user}/create/', ['as' => 'formulaires.create', 'uses' => 'FormulairesController@create']);
    Route::post('/formulaires/{user}/store/', ['as' => 'formulaires.store', 'uses' => 'FormulairesController@store']);
    Route::resource('/analyses','AnalysesController', ['except' => ['show']]);
    Route::post('/analyses/sort', '\Rutorika\Sortable\SortableController@sort');
    Route::resource('/equipements','EquipementsController', ['except' => ['show']]);
});

app/Equipement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Equipement extends Model
{
    public $timestamps = false;

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function hasAnalyse($analyse_id)
    {
        foreach($this->analyses as $analyse) {
            if($analyse->id == $analyse_id) {
                return true;
            }
        }

        return false;
    }
}

app/Http/Controllers/Admin/EquipementsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Equipement;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class EquipementsController extends Controller
{
    /**
     * Display a listing of the equipements
     *
     * @param  \App\Equipement $model
     * @return \Illuminate\View\View
     */
    public function index(Equipement $model)
    {
        return view('admin.equipements.index', ['equipements' => $model->all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Equipement  $equipement
     * @return \Illuminate\Http\Response
     */
    public function show(Materiel $equipement)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Equipement  $equipement
     * @return \Illuminate\Http\Response
     */
    public function edit(Equipement $equipement)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Equipement  $equipement
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Equipement $equipement)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Equipement  $equipement
     * @return \Illuminate\Http\Response
     */
    public function destroy(Equipement $equipement)
    {
        //
    }
}

resources/views/admin/equipements/index.blade.php
@extends('layouts.app', ['activePage' => 'equipements', 'titlePage' => __('equipements')])

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Équipements <a href="{{ route('admin.equipements.create') }}" class="btn btn-primary float-right">Ajouter</a></div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Nom</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($equipements as $equipement)
                            <tr>
                                <th scope="row">{{ $equipement->nom }}</th>
                                <td>
                                    <a href="{{ route('admin.equipements.edit', $equipement->id) }}"><button type="button" class="btn btn-link float-left"><i class="fa fa-pencil"></i></button></a>
                                    <form action="{{ route('admin.equipements.destroy', $equipement) }}" method="POST" class="float-left">
                                        @csrf
                                        @method('delete')
                                        <button type="button" class="btn btn-link" onclick="confirm('{{ __("Êtes-vous certain de vouloir supprimer cette equipement?") }}') ? this.parentElement.submit() : ''"><i class="fa fa-trash-o"></i></button>
                                    </form>
                                </td>
                            </tr>
                        @endForeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection