routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/', 'HomeController@index')->name('home')->middleware('auth');
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');


Route::group(['middleware' => 'auth'], function () {
    Route::get('/users/list', ['as' => 'users.list', 'uses' => 'UserController@list']);
    Route::get('/user/{user}/edit', ['as' => 'user.edit', 'uses' => 'UserController@edit']);
    Route::post('/user/{user}/update', ['as' => 'user.update', 'uses' => 'UserController@update']);
    Route::get('/rapports', ['as' => 'rapports.index', 'uses' => 'RapportsController@index']);
    Route::get('/rapports/{rapport}', ['as' => 'rapports.show', 'uses' => 'RapportsController@show']);
    Route::get('/rapports/{rapport}/export', ['as' => 'rapports.export', 'uses' => 'RapportsController@export']);
    Route::get('/rapports/{rapport}/edit', ['as' => 'rapports.edit', 'uses' => 'RapportsController@edit']);
    Route::post('/rapports/{rapport}/{user}/update', ['as' => 'rapports.update', 'uses' => 'RapportsController@update']);
    Route::get('/rapports/{client}/list', ['as' => 'rapports.list', 'uses' => 'RapportsController@list']);
    Route::get('/rapports/{user}/create', ['as' => 'rapports.create', 'uses' => 'RapportsController@create']);
    Route::post('/rapports/{user}/store', ['as' => 'rapports.store', 'uses' => 'RapportsController@store']);
    Route::get('/stats/{client}/{range?}', ['as' => 'stats', 'uses' => 'HomeController@stats']);
});

Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function(){
    Route::resource('/users', 'UsersController', ['except' => ['create', 'store']]);
    Route::get('/users/{type}/create', ['as' => 'users.create', 'uses' => 'UsersController@create']);
    Route::post('/users/{type}/store', ['as' => 'users.store', 'uses' => 'UsersController@store']);
    Route::post('/users/{user}/{type}/destroy', ['as' => 'users.destroy', 'uses' => 'UsersController@destroy']);
    Route::get('/users/list/{type}', ['as' => 'users.list', 'uses' => 'UsersController@list']);
    Route::resource('/formulaires','FormulairesController', ['except' => ['show', 'create', 'store']]);
    Route::get('/formulaires/{user}/create/', ['as' => 'formulaires.create', 'uses' => 'FormulairesController@create']);
    Route::post('/formulaires/{user}/store/', ['as' => 'formulaires.store', 'uses' => 'FormulairesController@store']);
    Route::resource('/analyses','AnalysesController', ['except' => ['show']]);
    Route::post('/analyses/sort', '\Rutorika\Sortable\SortableController@sort');
    Route::resource('/equipements','EquipementsController', ['except' => ['show']]);
});

app/Http/Controllers/Admin/AnalysesController.php
<?php

namespace App\Http\Controllers\Admin;

use Gate;
use App\Analyse;
use App\Equipement;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\AnalyseRequest;

class AnalysesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $analyses = Analyse::sorted()->get();

        return view('admin.analyses.index', compact('analyses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Gate::denies('edit-users')){
            return redirect()->route('admin.analyses.index');
        }

        $equipements = Equipement::all();

        return view('admin.analyses.create', compact('equipements'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Analyse::create($request->all());

        return redirect()->route('admin.analyses.index')->withStatus(__('Nouvelle analyse ajoutée.'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Analyse $analysis)
    {
        if(Gate::denies('edit-users')){
            return redirect()->route('admin.analyses.index');
        }

        $analyse = $analysis;
        $equipements = Equipement::all();

        return view('admin.analyses.edit', compact(['analyse', 'equipements']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AnalyseRequest $request, Analyse $analysis)
    {
        $analysis->update($request->all());

        return redirect()->route('admin.analyses.index')->withStatus(__('Analyse sauvegardée'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Analyse $analysis)
    {
        $analysis->delete();

        return redirect()->route('admin.analyses.index')->withStatus(__('Analyse supprimée.'));
    }
}

resources/views/admin/analyses/create.blade.php
@extends('layouts.app', ['activePage' => 'analyses', 'titlePage' => __('Analyses')])

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Nouvelle analyse</div>
                <div class="card-body">
                    <form action="{{ route('admin.analyses.store') }}" method="POST">
                        @csrf
                        @method('post')
                        <div class="form-group">
                            <label for="input-nom">Nom</label>
                            <input type="text" class="form-control" id="input-nom" name="nom">
                        </div>
                        <div class="form-group">
                            <label for="input-titre">Titre</label>
                            <input type="text" class="form-control" id="input-titre" name="titre">
                        </div>
                        <div class="form-group">
                            <label for="type">Type</label>
                            <select id="type" class="form-control" name="type">
                                <option value="text">Texte / numérique</option>
                                <option value="checkbox">Check Box</option>
                                <option value="select">Dropdown</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="equipement_id">Équipement</label>
                            <select id="equipement_id" class="form-control" name="equipement_id">
                                <option value="0" selected="selected">Tous les équipements</option>
                                @foreach($equipements as $equipement)
                                    <option value="{{ $equipement->id }}">{{ $equipement->nom }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="groupe">Groupe</label>
                            <select id="groupe" class="form-control" nom="groupe">
                                <option value="materiel" selected="selected">Matériel</option>
                                <option value="chimique">Produit chimique</option>
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary">Sauvegarder</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/analyses/edit.blade.php
@extends('layouts.app', ['activePage' => 'analyses', 'titlePage' => __('Analyses')])

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Édition de l'analyse <strong>{{ $analyse->titre }}</strong></div>
                <div class="card-body">
                    <form action="{{ route('admin.analyses.update', $analyse) }}" method="post">
                        @csrf
                        @method('put')

                        <div class="form-group">
                            <label for="nom">Nom</label>
                            <input type="text" class="form-control" id="nom" name="nom" value="{{ old('nom', $analyse->nom) }}">
                        </div>
                        <div class="form-group">
                            <label for="titre">Titre</label>
                            <input type="text" class="form-control" id="titre" name="titre" value="{{ old('titre', $analyse->titre) }}">
                        </div>
                        <div class="form-group">
                            <label for="type">Type</label>
                            <select id="type" name="type" class="form-control">
                                <option value="text" {{ $analyse->type == 'text' ? 'checked="checked"' : '' }}>Texte / numérique</option>
                                <option value="checkbox" {{ $analyse->type == 'checkbox' ? 'checked="checked"' : '' }}>Check Box</option>
                                <option value="select" {{ $analyse->type == 'select' ? 'checked="checked"' : '' }}>Dropdown</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="equipement_id">Équipement</label>
                            <select id="equipement_id" name="equipement_id" class="form-control">
                                <option value="0">Tous les équipements</option>
                                @foreach($equipements as $equipement)
                                    <option value="{{ $equipement->id }}" {{ $equipement->id == $analyse->equipement_id ? 'checked="checked"' : '' }}>{{ $equipement->nom }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="groupe">Groupe</label>
                            <select id="groupe" name="groupe" class="form-control">
                                <option value="materiel" {{ $analyse->groupe == 'materiel' ? 'checked="checked"' : '' }}>Matériel</option>
                                <option value="chimique" {{ $analyse->groupe == 'chimique' ? 'checked="checked"' : '' }}>Produit chimique</option>
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary">Sauvegarder</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/analyses/index.blade.php
@extends('layouts.app', ['activePage' => 'analyses', 'titlePage' => __('Analyses')])

@section('content')

    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Analyses <a href="{{ route('admin.analyses.create') }}" class="btn btn-primary float-right">Ajouter</a></div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Ordre</th>
                                <th scope="col">Titre</th>
                                <th scope="col">Nom</th>
                                <th scope="col">Type</th>
                                <th scope="col">Groupe</th>
                            </tr>
                        </thead>
                        <tbody class="sortable" data-entityname="analyse">
                        @foreach($analyses as $analyse)
                            <tr data-itemId="{{{ $analyse->id }}}">
                                <td class="sortable-handle"><i class="fa fa-sort"></i></td>
                                <td class="id-column" style="display:none;">{{ $analyse->id }}</td>
                                <th scope="row">{{ $analyse->titre }}</td>
                                <td>{{ $analyse->nom }}</th>
                                <td>{{ $analyse->type }}</td>
                                <td>{{ $analyse->groupe }}</td>
                                <td>
                                    <a href="{{ route('admin.analyses.edit', $analyse) }}"><button type="button" class="btn btn-link"><i class="fa fa-pencil"></i></button></a>
                                    <form action="{{ route('admin.analyses.destroy', $analyse) }}" method="POST" class="float-left">
                                        @csrf
                                        @method('delete')
                                        <button type="button" class="btn btn-link" onclick="confirm('{{ __("Êtes-vous certain de vouloir supprimer cette analyse?") }}') ? this.parentElement.submit() : ''"><i class="fa fa-trash-o"></i></button>
                                    </form>
                                </td>
                            </tr>
                        @endForeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

@endsection
@push('scripts')
<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
  integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
  crossorigin="anonymous"></script>
<script>
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
    /**
     *
     * @param type string 'insertAfter' or 'insertBefore'
     * @param entityName
     * @param id
     * @param positionId
     */
     var changePosition = function(requestData){
        $.ajax({
            'url': '/admin/analyses/sort',
            'type': 'POST',
            'data': requestData,
            'success': function(data) {
                if (data.success) {
                    console.log('Saved!');
                } else {
                    console.error(data.errors);
                }
            },
            'error': function(){
                console.error('Something wrong!');
            }
        });
    };

    $(document).ready(function(){
        var $sortableTable = $('.sortable');
        if ($sortableTable.length > 0) {
            $sortableTable.sortable({
                handle: '.sortable-handle',
                axis: 'y',
                update: function(a, b){

                    var entityName = $(this).data('entityname');
                    var $sorted = b.item;

                    var $previous = $sorted.prev();
                    var $next = $sorted.next();

                    if ($previous.length > 0) {
                        changePosition({
                            parentId: $sorted.data('parentid'),
                            type: 'moveAfter',
                            entityName: entityName,
                            id: $sorted.data('itemid'),
                            positionEntityId: $previous.data('itemid')
                        });
                    } else if ($next.length > 0) {
                        changePosition({
                            parentId: $sorted.data('parentid'),
                            type: 'moveBefore',
                            entityName: entityName,
                            id: $sorted.data('itemid'),
                            positionEntityId: $next.data('itemid')
                        });
                    } else {
                        console.error('Something wrong!');
                    }
                },
                cursor: "move"
            });
        }
    });
</script>
@endPush